{% set version = "0.0.0" %}
{% set sha256 = "TODO" %}

package:
  name: asap
  version: '{{ version }}'

source:
  #url: https://github.com/TGenNorth/ASAP/archive/v{{ version }}.tar.gz
  #sha256: '{{ sha256 }}'
  path: .
  patches:
    - disable_setuptools_scm.patch

build:
  noarch: python
  number: 0
  script:
    - echo 'version = "{{ version }}"' > asap/version.py
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python 3.*
    - pip
  run:
    - python 3.*
    - numpy
    - pysam >0.13
    - scikit-bio
    - openpyxl
    - lxml
    - samtools >=1.0
    - trimmomatic
    - bowtie2

test:
  imports:
    - asap
  commands:
    - bamProcessor --help
    - analyzeAmplicons --help
    - bamProcessor --help
    - formatOutput --help
    - outputCombiner --help
    - prepareJSONInput --help
    - reformatXML --help

about:
  home: https://github.com/TGenNorth/ASAP
  summary: Amplicon Sequencing Analysis Pipeline
  license: Academic and Research License
  license_family: Other
  license_file: LICENSE

extra:
  identifiers:
    # TODO: https://zenodo.org
    - doi:...
  recipe-maintainers:
    - corburn
    - DarwinW13
